package sheffield.service;

import java.util.List;

import sheffield.mbg.pojo.Address;

public interface AddressService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table address
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	int deleteByPrimaryKey(Long addressid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table address
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	int insert(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table address
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	Address selectByPrimaryKey(Long addressid);;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table address
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	List<Address> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table address
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	int updateByPrimaryKey(Address record);
	
	List<Address> selectByUserId(long userid);
	Address selectByAddressDescription(String addressdescription);
	
}
