package sheffield.service;

import java.util.LinkedList;
import java.util.List;

import sheffield.mbg.pojo.Commodityimage;

public interface CommodityimageService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	int deleteByPrimaryKey(Long commodityimgid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	int insert(Commodityimage record);

	 List<Commodityimage> insertMultipleImagesForCommodity(LinkedList<Commodityimage> list,Long commodityid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	Commodityimage selectByPrimaryKey(Long commodityimgid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	List<Commodityimage> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	int updateByPrimaryKey(Commodityimage record);

	List<Commodityimage> selectByCommodityId(Long commodityid);

	 List<Commodityimage> deleteByCommodityIdThenInsertMultipleImagesForCommodity(Long commodityid, LinkedList<Commodityimage> list);
	List<Long> selectImgKeysByCommodityId(Long commodityid);
}
