package sheffield.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import sheffield.mbg.pojo.Commodity;

public interface CommodityService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public int deleteByPrimaryKey(Long commodityid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	Commodity insertThenCachePut(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	Commodity selectByPrimaryKey(Long commodityid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	List<Commodity> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	int updateByPrimaryKey(Commodity record);

	long returnPrimaryKeyByCommodity(Commodity record);

	List<Commodity> selectByOwnerId(Long commodityownerid);

	public Commodity updateForVersionByPrimaryKeyAndVersion(Commodity record, long version);

	List<Commodity> selectByUsingFullTextOrderBySales(String searchcontent, Integer limitoffset, Integer limitsize);

	List<Commodity> selectByUsingFullTextOrderByDate(String searchcontent, Integer limitoffset, Integer limitsize);

	List<Commodity> selectByUsingFullTextOrderByPriceDESC(String searchcontent, Integer limitoffset, Integer limitsize);

	List<Commodity> selectByUsingFullTextOrderByPriceASC(String searchcontent, Integer limitoffset, Integer limitsize);

	List<Commodity> selectAllBySales(Integer limitoffset, Integer limitsize);

	Double selectRateBySearch(Long commodityid);

	Integer countBySearch(String searchcontent);

	Integer countAll();

	List<Commodity> selectForHomePage(Integer limitoffset, Integer limitsize);

	List<Commodity> searchByPriceRange(String searchcontent,Double fromprice, Double toprice, Integer limitoffset, Integer limitsize);

}
