package sheffield.service;

import java.util.List;

import sheffield.mbg.pojo.Permission;

public interface PermissionService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table permission
	 *
	 * @mbg.generated Mon Dec 11 13:45:45 GMT 2017
	 */
	int deleteByPrimaryKey(Long userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table permission
	 *
	 * @mbg.generated Mon Dec 11 13:45:45 GMT 2017
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table permission
	 *
	 * @mbg.generated Mon Dec 11 13:45:45 GMT 2017
	 */
	Permission selectByPrimaryKey(Long userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table permission
	 *
	 * @mbg.generated Mon Dec 11 13:45:45 GMT 2017
	 */
	List<Permission> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table permission
	 *
	 * @mbg.generated Mon Dec 11 13:45:45 GMT 2017
	 */
	int updateByPrimaryKey(Permission record);

	public List<String> findRoles(Long userid);

	public List<String> findPermissions(Long userid);
	
}
