/**
 * 
 */
package sheffield.service;

import java.util.List;

import sheffield.mbg.pojo.Ptransaction;

/**
 * @author Redfiska
 *
 */
public interface PtransactionService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ptransaction
	 *
	 * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
	 */
	int deleteByPrimaryKey(Long ptransactionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ptransaction
	 *
	 * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
	 */
	int insert(Ptransaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ptransaction
	 *
	 * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
	 */
	Ptransaction selectByPrimaryKey(Long ptransactionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ptransaction
	 *
	 * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
	 */
	List<Ptransaction> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ptransaction
	 *
	 * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
	 */
	int updateByPrimaryKey(Ptransaction record);

	List<Ptransaction> selectByUserId(Long userid);

}
