package sheffield.service;

import java.util.List;

import org.springframework.transaction.annotation.Transactional;

import sheffield.mbg.pojo.Transaction;

public interface TransactionService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table transaction
	 *
	 * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
	 */
	int deleteByPrimaryKey(Long transactionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table transaction
	 *
	 * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
	 */
	int insert(Transaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table transaction
	 *
	 * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
	 */
	Transaction selectByPrimaryKey(Long transactionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table transaction
	 *
	 * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
	 */
	List<Transaction> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table transaction
	 *
	 * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
	 */

	
	int updateByPrimaryKey(Transaction record);

	int createTransaction(Transaction record, long buyerid, long commodityid);

	List<Transaction> selectByUserIdOrderByTransactionDate(long userid);

	List<Transaction> selectByCommodityIdOrderByTransactionDate(long commodityid);

	List<Transaction> selectByCommodityOwnerIdOrderByTransactionDate(long commodityownerid);

}
