package sheffield.service;

import java.util.List;

import sheffield.mbg.pojo.User;

public interface UserService {
	int deleteByPrimaryKey(Long userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Sun Dec 10 20:39:27 GMT 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Sun Dec 10 20:39:27 GMT 2017
	 */
	User selectByPrimaryKey(Long userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Sun Dec 10 20:39:27 GMT 2017
	 */
	List<User> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Sun Dec 10 20:39:27 GMT 2017
	 */
	int updateByPrimaryKey(User record);

	public User selectByUserName(String username);

	public int updateUserWithLock(Long userid, User newuser);
	
	Integer selectExistsByUserName(String username);
	
	List<Long> selectAllUserId();

}
