package sheffield.mbg.pojo;

public class Account {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column account.accountId
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	private Long accountid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column account.userId
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	private Long userid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column account.peanut
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	private Double peanut;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column account.credit
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	private Double credit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column account.accountId
	 *
	 * @return the value of account.accountId
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public Long getAccountid() {
		return accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column account.accountId
	 *
	 * @param accountid
	 *            the value for account.accountId
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public void setAccountid(Long accountid) {
		this.accountid = accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column account.userId
	 *
	 * @return the value of account.userId
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column account.userId
	 *
	 * @param userid
	 *            the value for account.userId
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column account.peanut
	 *
	 * @return the value of account.peanut
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public Double getPeanut() {
		return peanut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column account.peanut
	 *
	 * @param peanut
	 *            the value for account.peanut
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public void setPeanut(Double peanut) {
		this.peanut = peanut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column account.credit
	 *
	 * @return the value of account.credit
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public Double getCredit() {
		return credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column account.credit
	 *
	 * @param credit
	 *            the value for account.credit
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	public void setCredit(Double credit) {
		this.credit = credit;
	}
}