package sheffield.mbg.pojo;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Long addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressDescription
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private String addressdescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressId
     *
     * @return the value of address.addressId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Long getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressId
     *
     * @param addressid the value for address.addressId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setAddressid(Long addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userId
     *
     * @return the value of address.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userId
     *
     * @param userid the value for address.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressDescription
     *
     * @return the value of address.addressDescription
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public String getAddressdescription() {
        return addressdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressDescription
     *
     * @param addressdescription the value for address.addressDescription
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setAddressdescription(String addressdescription) {
        this.addressdescription = addressdescription;
    }
}