package sheffield.mbg.pojo;

import java.io.Serializable;

public class Commodityimage implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodityimage.commodityImgId
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    private Long commodityimgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodityimage.commodityId
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    private Long commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodityimage.commodityImgName
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    private String commodityimgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodityimage.commodityImgDate
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    private String commodityimgdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodityimage.version
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodityimage.commodityImg
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    private byte[] commodityimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodityimage.commodityImgId
     *
     * @return the value of commodityimage.commodityImgId
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public Long getCommodityimgid() {
        return commodityimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodityimage.commodityImgId
     *
     * @param commodityimgid the value for commodityimage.commodityImgId
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public void setCommodityimgid(Long commodityimgid) {
        this.commodityimgid = commodityimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodityimage.commodityId
     *
     * @return the value of commodityimage.commodityId
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public Long getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodityimage.commodityId
     *
     * @param commodityid the value for commodityimage.commodityId
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public void setCommodityid(Long commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodityimage.commodityImgName
     *
     * @return the value of commodityimage.commodityImgName
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public String getCommodityimgname() {
        return commodityimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodityimage.commodityImgName
     *
     * @param commodityimgname the value for commodityimage.commodityImgName
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public void setCommodityimgname(String commodityimgname) {
        this.commodityimgname = commodityimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodityimage.commodityImgDate
     *
     * @return the value of commodityimage.commodityImgDate
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public String getCommodityimgdate() {
        return commodityimgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodityimage.commodityImgDate
     *
     * @param commodityimgdate the value for commodityimage.commodityImgDate
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public void setCommodityimgdate(String commodityimgdate) {
        this.commodityimgdate = commodityimgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodityimage.version
     *
     * @return the value of commodityimage.version
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodityimage.version
     *
     * @param version the value for commodityimage.version
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodityimage.commodityImg
     *
     * @return the value of commodityimage.commodityImg
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public byte[] getCommodityimg() {
        return commodityimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodityimage.commodityImg
     *
     * @param commodityimg the value for commodityimage.commodityImg
     *
     * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
     */
    public void setCommodityimg(byte[] commodityimg) {
        this.commodityimg = commodityimg;
    }
}