package sheffield.mbg.pojo;

import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import org.springframework.data.annotation.Id;

public class CommodityWithRate {

	public CommodityWithRate() {
		// TODO Auto-generated constructor stub
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityId
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	@Id
	private Long commodityid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityName
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */

	@NotBlank
	@Size(min = 1, max = 50)
	private String commodityname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityDate
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */

	private String commoditydate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityPrice
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */

	@DecimalMin("0")
	private Double commodityprice;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityQuantity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */

	@DecimalMin("0")
	private Double commodityquantity;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityOwnerId
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	private Long commodityownerid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityCategory
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	@NotBlank
	private String commoditycategory;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commoditySales
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */

	private Double commoditysales;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityLocation
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */

	@NotBlank
	private String commoditylocation;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.version
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	private Long version;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column commodity.commodityDescription
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	@NotBlank
	@Size(min = 1, max = 300)
	// @Field
	// 暂时决定在elasticsearch索引中存储商品描述
	private String commoditydescription;

	private int rate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityId
	 *
	 * @return the value of commodity.commodityId
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public Long getCommodityid() {
		return commodityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityId
	 *
	 * @param commodityid
	 *            the value for commodity.commodityId
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommodityid(Long commodityid) {
		this.commodityid = commodityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityName
	 *
	 * @return the value of commodity.commodityName
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public String getCommodityname() {
		return commodityname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityName
	 *
	 * @param commodityname
	 *            the value for commodity.commodityName
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommodityname(String commodityname) {
		this.commodityname = commodityname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityDate
	 *
	 * @return the value of commodity.commodityDate
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public String getCommoditydate() {
		return commoditydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityDate
	 *
	 * @param commoditydate
	 *            the value for commodity.commodityDate
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommoditydate(String commoditydate) {
		this.commoditydate = commoditydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityPrice
	 *
	 * @return the value of commodity.commodityPrice
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public Double getCommodityprice() {
		return commodityprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityPrice
	 *
	 * @param commodityprice
	 *            the value for commodity.commodityPrice
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommodityprice(Double commodityprice) {
		this.commodityprice = commodityprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityQuantity
	 *
	 * @return the value of commodity.commodityQuantity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public Double getCommodityquantity() {
		return commodityquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityQuantity
	 *
	 * @param commodityquantity
	 *            the value for commodity.commodityQuantity
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommodityquantity(Double commodityquantity) {
		this.commodityquantity = commodityquantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityOwnerId
	 *
	 * @return the value of commodity.commodityOwnerId
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public Long getCommodityownerid() {
		return commodityownerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityOwnerId
	 *
	 * @param commodityownerid
	 *            the value for commodity.commodityOwnerId
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommodityownerid(Long commodityownerid) {
		this.commodityownerid = commodityownerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityCategory
	 *
	 * @return the value of commodity.commodityCategory
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public String getCommoditycategory() {
		return commoditycategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityCategory
	 *
	 * @param commoditycategory
	 *            the value for commodity.commodityCategory
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommoditycategory(String commoditycategory) {
		this.commoditycategory = commoditycategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commoditySales
	 *
	 * @return the value of commodity.commoditySales
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public Double getCommoditysales() {
		return commoditysales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commoditySales
	 *
	 * @param commoditysales
	 *            the value for commodity.commoditySales
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommoditysales(Double commoditysales) {
		this.commoditysales = commoditysales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityLocation
	 *
	 * @return the value of commodity.commodityLocation
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public String getCommoditylocation() {
		return commoditylocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityLocation
	 *
	 * @param commoditylocation
	 *            the value for commodity.commodityLocation
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommoditylocation(String commoditylocation) {
		this.commoditylocation = commoditylocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.version
	 *
	 * @return the value of commodity.version
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public Long getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.version
	 *
	 * @param version
	 *            the value for commodity.version
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setVersion(Long version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column commodity.commodityDescription
	 *
	 * @return the value of commodity.commodityDescription
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public String getCommoditydescription() {
		return commoditydescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column commodity.commodityDescription
	 *
	 * @param commoditydescription
	 *            the value for commodity.commodityDescription
	 *
	 * @mbg.generated Thu Dec 14 14:37:53 GMT 2017
	 */
	public void setCommoditydescription(String commoditydescription) {
		this.commoditydescription = commoditydescription;
	}

	public int getRate() {
		return rate;
	}

	public void setRate(int rate) {
		this.rate = rate;
	}
}
