package sheffield.mbg.pojo;

import java.io.Serializable;

public class Grabredpacket implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabredpacket.grabredPacketId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    private Long grabredpacketid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabredpacket.senderId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    private Long senderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabredpacket.recipientId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    private Long recipientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabredpacket.redpacketMoney
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    private Double redpacketmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabredpacket.redpacketTime
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    private String redpackettime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabredpacket.reapacketNote
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    private String reapacketnote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabredpacket.grabredPacketId
     *
     * @return the value of grabredpacket.grabredPacketId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public Long getGrabredpacketid() {
        return grabredpacketid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabredpacket.grabredPacketId
     *
     * @param grabredpacketid the value for grabredpacket.grabredPacketId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public void setGrabredpacketid(Long grabredpacketid) {
        this.grabredpacketid = grabredpacketid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabredpacket.senderId
     *
     * @return the value of grabredpacket.senderId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public Long getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabredpacket.senderId
     *
     * @param senderid the value for grabredpacket.senderId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public void setSenderid(Long senderid) {
        this.senderid = senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabredpacket.recipientId
     *
     * @return the value of grabredpacket.recipientId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public Long getRecipientid() {
        return recipientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabredpacket.recipientId
     *
     * @param recipientid the value for grabredpacket.recipientId
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public void setRecipientid(Long recipientid) {
        this.recipientid = recipientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabredpacket.redpacketMoney
     *
     * @return the value of grabredpacket.redpacketMoney
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public Double getRedpacketmoney() {
        return redpacketmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabredpacket.redpacketMoney
     *
     * @param redpacketmoney the value for grabredpacket.redpacketMoney
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public void setRedpacketmoney(Double redpacketmoney) {
        this.redpacketmoney = redpacketmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabredpacket.redpacketTime
     *
     * @return the value of grabredpacket.redpacketTime
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public String getRedpackettime() {
        return redpackettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabredpacket.redpacketTime
     *
     * @param redpackettime the value for grabredpacket.redpacketTime
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public void setRedpackettime(String redpackettime) {
        this.redpackettime = redpackettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabredpacket.reapacketNote
     *
     * @return the value of grabredpacket.reapacketNote
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public String getReapacketnote() {
        return reapacketnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabredpacket.reapacketNote
     *
     * @param reapacketnote the value for grabredpacket.reapacketNote
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    public void setReapacketnote(String reapacketnote) {
        this.reapacketnote = reapacketnote;
    }
}