package sheffield.mbg.pojo;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permissionId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Long permissionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permissions
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private String permissions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.roles
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private String roles;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permissionId
     *
     * @return the value of permission.permissionId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Long getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permissionId
     *
     * @param permissionid the value for permission.permissionId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setPermissionid(Long permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.userId
     *
     * @return the value of permission.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.userId
     *
     * @param userid the value for permission.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permissions
     *
     * @return the value of permission.permissions
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permissions
     *
     * @param permissions the value for permission.permissions
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.roles
     *
     * @return the value of permission.roles
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.roles
     *
     * @param roles the value for permission.roles
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setRoles(String roles) {
        this.roles = roles;
    }
}