package sheffield.mbg.pojo;

public class Ptransaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptransaction.ptransactionId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    private Long ptransactionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptransaction.ptransactionDate
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    private String ptransactiondate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptransaction.userId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptransaction.providerId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    private Long providerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptransaction.appName
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptransaction.peanutsUsed
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    private Double peanutsused;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptransaction.ptransactionId
     *
     * @return the value of ptransaction.ptransactionId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public Long getPtransactionid() {
        return ptransactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptransaction.ptransactionId
     *
     * @param ptransactionid the value for ptransaction.ptransactionId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public void setPtransactionid(Long ptransactionid) {
        this.ptransactionid = ptransactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptransaction.ptransactionDate
     *
     * @return the value of ptransaction.ptransactionDate
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public String getPtransactiondate() {
        return ptransactiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptransaction.ptransactionDate
     *
     * @param ptransactiondate the value for ptransaction.ptransactionDate
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public void setPtransactiondate(String ptransactiondate) {
        this.ptransactiondate = ptransactiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptransaction.userId
     *
     * @return the value of ptransaction.userId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptransaction.userId
     *
     * @param userid the value for ptransaction.userId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptransaction.providerId
     *
     * @return the value of ptransaction.providerId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public Long getProviderid() {
        return providerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptransaction.providerId
     *
     * @param providerid the value for ptransaction.providerId
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public void setProviderid(Long providerid) {
        this.providerid = providerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptransaction.appName
     *
     * @return the value of ptransaction.appName
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptransaction.appName
     *
     * @param appname the value for ptransaction.appName
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptransaction.peanutsUsed
     *
     * @return the value of ptransaction.peanutsUsed
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public Double getPeanutsused() {
        return peanutsused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptransaction.peanutsUsed
     *
     * @param peanutsused the value for ptransaction.peanutsUsed
     *
     * @mbg.generated Thu Feb 22 15:00:07 GMT 2018
     */
    public void setPeanutsused(Double peanutsused) {
        this.peanutsused = peanutsused;
    }
}