package sheffield.mbg.pojo;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.reviewId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Long reviewid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.commodityId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Long commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.reviewDate
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private String reviewdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.rate
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private Integer rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.customerReview
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    private String customerreview;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.reviewId
     *
     * @return the value of review.reviewId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Long getReviewid() {
        return reviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.reviewId
     *
     * @param reviewid the value for review.reviewId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setReviewid(Long reviewid) {
        this.reviewid = reviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.userId
     *
     * @return the value of review.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.userId
     *
     * @param userid the value for review.userId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.commodityId
     *
     * @return the value of review.commodityId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Long getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.commodityId
     *
     * @param commodityid the value for review.commodityId
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setCommodityid(Long commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.reviewDate
     *
     * @return the value of review.reviewDate
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public String getReviewdate() {
        return reviewdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.reviewDate
     *
     * @param reviewdate the value for review.reviewDate
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setReviewdate(String reviewdate) {
        this.reviewdate = reviewdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.rate
     *
     * @return the value of review.rate
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.rate
     *
     * @param rate the value for review.rate
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.customerReview
     *
     * @return the value of review.customerReview
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public String getCustomerreview() {
        return customerreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.customerReview
     *
     * @param customerreview the value for review.customerReview
     *
     * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
     */
    public void setCustomerreview(String customerreview) {
        this.customerreview = customerreview;
    }
}