package sheffield.mbg.pojo;

public class Transaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private Long transactionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionDate
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private String transactiondate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionName
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private String transactionname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.userId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.commodityId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private Long commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionSum
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private Double transactionsum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionAmount
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private Double transactionamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.addressId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private Long addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionStatus
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private String transactionstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionDescription
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    private String transactiondescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionId
     *
     * @return the value of transaction.transactionId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public Long getTransactionid() {
        return transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionId
     *
     * @param transactionid the value for transaction.transactionId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setTransactionid(Long transactionid) {
        this.transactionid = transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionDate
     *
     * @return the value of transaction.transactionDate
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public String getTransactiondate() {
        return transactiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionDate
     *
     * @param transactiondate the value for transaction.transactionDate
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setTransactiondate(String transactiondate) {
        this.transactiondate = transactiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionName
     *
     * @return the value of transaction.transactionName
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public String getTransactionname() {
        return transactionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionName
     *
     * @param transactionname the value for transaction.transactionName
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setTransactionname(String transactionname) {
        this.transactionname = transactionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.userId
     *
     * @return the value of transaction.userId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.userId
     *
     * @param userid the value for transaction.userId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.commodityId
     *
     * @return the value of transaction.commodityId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public Long getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.commodityId
     *
     * @param commodityid the value for transaction.commodityId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setCommodityid(Long commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionSum
     *
     * @return the value of transaction.transactionSum
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public Double getTransactionsum() {
        return transactionsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionSum
     *
     * @param transactionsum the value for transaction.transactionSum
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setTransactionsum(Double transactionsum) {
        this.transactionsum = transactionsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionAmount
     *
     * @return the value of transaction.transactionAmount
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public Double getTransactionamount() {
        return transactionamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionAmount
     *
     * @param transactionamount the value for transaction.transactionAmount
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setTransactionamount(Double transactionamount) {
        this.transactionamount = transactionamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.addressId
     *
     * @return the value of transaction.addressId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public Long getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.addressId
     *
     * @param addressid the value for transaction.addressId
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setAddressid(Long addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionStatus
     *
     * @return the value of transaction.transactionStatus
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public String getTransactionstatus() {
        return transactionstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionStatus
     *
     * @param transactionstatus the value for transaction.transactionStatus
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setTransactionstatus(String transactionstatus) {
        this.transactionstatus = transactionstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionDescription
     *
     * @return the value of transaction.transactionDescription
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public String getTransactiondescription() {
        return transactiondescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionDescription
     *
     * @param transactiondescription the value for transaction.transactionDescription
     *
     * @mbg.generated Thu Jan 04 16:31:14 GMT 2018
     */
    public void setTransactiondescription(String transactiondescription) {
        this.transactiondescription = transactiondescription;
    }
}