package sheffield.mbg.pojo;

import java.io.Serializable;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

public class User implements Serializable{
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.userId
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	private Long userid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.userName
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	@NotBlank
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.userEmail
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	@Email
	private String useremail;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.userPassword
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	@NotBlank
	@Size(min = 6, max = 12)
	private String userpassword;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.userAvatar
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	private byte[] useravatar;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.userId
	 *
	 * @return the value of user.userId
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.userId
	 *
	 * @param userid
	 *            the value for user.userId
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.userName
	 *
	 * @return the value of user.userName
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.userName
	 *
	 * @param username
	 *            the value for user.userName
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.userEmail
	 *
	 * @return the value of user.userEmail
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public String getUseremail() {
		return useremail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.userEmail
	 *
	 * @param useremail
	 *            the value for user.userEmail
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public void setUseremail(String useremail) {
		this.useremail = useremail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.userPassword
	 *
	 * @return the value of user.userPassword
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public String getUserpassword() {
		return userpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.userPassword
	 *
	 * @param userpassword
	 *            the value for user.userPassword
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.userAvatar
	 *
	 * @return the value of user.userAvatar
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public byte[] getUseravatar() {
		return useravatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.userAvatar
	 *
	 * @param useravatar
	 *            the value for user.userAvatar
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	public void setUseravatar(byte[] useravatar) {
		this.useravatar = useravatar;
	}
}