package sheffield.mbg.dao;

import java.util.List;
import sheffield.mbg.pojo.Account;

public interface AccountMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table account
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	int deleteByPrimaryKey(Long accountid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table account
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	int insert(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table account
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	Account selectByPrimaryKey(Long accountid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table account
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	List<Account> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table account
	 *
	 * @mbg.generated Mon Dec 11 17:36:45 GMT 2017
	 */
	int updateByPrimaryKey(Account record);

	Account selectByUserId(long userid);
}