package sheffield.mbg.dao;

import java.util.List;
import sheffield.mbg.pojo.Commodityimage;

public interface CommodityimageMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	int deleteByPrimaryKey(Long commodityimgid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	int insert(Commodityimage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	Commodityimage selectByPrimaryKey(Long commodityimgid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	List<Commodityimage> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table commodityimage
	 *
	 * @mbg.generated Thu Dec 14 13:33:39 GMT 2017
	 */
	int updateByPrimaryKey(Commodityimage record);

	List<Commodityimage> selectByCommodityId(Long commodityid);

	int deleteByCommodityId(Long commodityid);

	List<Long> selectImgKeysByCommodityId(Long commodityid);
}