package sheffield.mbg.dao;

import java.util.List;
import sheffield.mbg.pojo.Grabredpacket;

public interface GrabredpacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabredpacket
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    int deleteByPrimaryKey(Long grabredpacketid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabredpacket
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    Integer insert(Grabredpacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabredpacket
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    Grabredpacket selectByPrimaryKey(Long grabredpacketid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabredpacket
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    List<Grabredpacket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabredpacket
     *
     * @mbg.generated Thu Jan 11 15:43:01 GMT 2018
     */
    int updateByPrimaryKey(Grabredpacket record);
}