package sheffield.mbg.dao;

import java.util.List;
import sheffield.mbg.pojo.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Mon Dec 11 16:57:36 GMT 2017
     */
    int deleteByPrimaryKey(Long permissionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Mon Dec 11 16:57:36 GMT 2017
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Mon Dec 11 16:57:36 GMT 2017
     */
    Permission selectByPrimaryKey(Long permissionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Mon Dec 11 16:57:36 GMT 2017
     */
    List<Permission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Mon Dec 11 16:57:36 GMT 2017
     */
    int updateByPrimaryKey(Permission record);

	List<String> findRoles(Long userid);

	List<String> findPermissions(Long userid);
}