package sheffield.mbg.dao;

import java.util.List;
import sheffield.mbg.pojo.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	int deleteByPrimaryKey(Long userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	User selectByPrimaryKey(Long userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	List<User> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Tue Dec 12 15:50:29 GMT 2017
	 */
	int updateByPrimaryKey(User record);

	User selectUserWithLock(Long userid);

	User selectByUserName(String username);

	Integer selectExistsByUserName(String username);
	
	List<Long> selectAllUserId();
}